### PR TITLE
Fix #18 Remove 'module' and 'jsnext:main' targets 

### LINKED ISSUE #18: cssauron and babel
Ok so I am not sure where the problem comes from exactly but here is what I am experiencing

- In dev mode, I don't compile for an es5 target, so I don't run babel on the files, everything works as expected
- in production mode, I need to be compatible with `es5` so I need to give the `js` files to babel (and Uglify doesn't accept many `es6` features so it crashes when trying to minify the bundle)

The thing is, `cssauron` is imported as follow (in the generated `es2015` file in `/lib`)

```javascript
import * as cssauron from 'cssauron';
```
Which is then compiled, by `babel`, into 

```javascript
var cssauron = _interopRequireWildcard(_cssauron)/* it's missing '.default' here */
```

And so my app now crashes.
I really don't know where the problem lies (my babel config file? my typescript config file? the import of `cssauron`? ...)

Do you have any idea how I can deal with this? I think updating the import to 

```javascript
import cssauron from 'cssauron'
```
would fix the problem, but maybe it's not THE solution.

### PR DESCRIPTION
**Pull request by atomrc**
This will avoid any babel transpilation errors (related to the `import * as` of the cssauron lib

### CODE REVIEW

**Comment by atomrc** [comment]
I just removed the fields in the package.json. Do you think I should also remove the compilation steps related to `es2015`?

**Comment by TylorS** [comment]
Thanks for the PR @atromrc. I think removing the compilation steps would be good.

**Comment by TylorS** [comment]
@atomrc I sent you an invite to be a collaborator here and also gave you permissions on NPM for this package.

**Comment by atomrc** [comment]
@TylorS awesome thanks :)

**Pull request merged**
