### PR TITLE
Replace cssauron with tree-selector

### PR DESCRIPTION
**Pull request by jvanbruegge**
Pros:
- a lot smaller (see https://github.com/cyclejs/cyclejs/issues/787)
- faster (uses Type 3 grammar and Regex)
- written in Typescript
- maintained (by me)
- high code coverage (92% atm)
- all tests still pass

Cons:
- `:any(selector1, selector2, selector3)` pseudoselector not supported any more

### CODE REVIEW

**Comment by jvanbruegge** [comment]
@atomrc what do you think?

**Comment by atomrc** [comment]
@jvanbruegge Well, it looks good indeed. Let's merge :)

**Comment by jvanbruegge** [comment]
Cool, then I can update the version in cycle

**Comment by atomrc** [comment]
Published under `v3.0.0`

**Pull request merged**
