### PR TITLE
Add snabbdom to dependencies

### PR DESCRIPTION
**Pull request by jvanbruegge**
When using pnpm, typescript will throw an error because it cannot `import {VNode} from 'snabbdom/vnode'` because with pnpm packages can not rely on other packages that are not declared as either dependencies or peerDependencies

### CODE REVIEW

**Comment by jvanbruegge** [comment]
I have no idea why the tests fail, locally I can build just fine

**Comment by jvanbruegge** [comment]
@atomrc could you merge this? I fixed it

**Comment by atomrc** [comment]
Merged.

What was the problem? Since you forced-push I cannot see the diffs, I'd be curious to know :)

**Comment by jvanbruegge** [comment]
I dont really know myself, I though about it and `peerDependencies` are better suited than `dependencies` so this was the first force-push. Then just some linting stuff.

**Comment by atomrc** [comment]
Do you think a minor version update (4.2.0) is fine for this change?

**Comment by jvanbruegge** [comment]
Yes

**Comment by atomrc** [comment]
Published with version `4.2.0`

**Comment by jvanbruegge** [comment]
Thank you!

**Pull request merged**
