### PR TITLE
Update Snabbdom to v3

### PR DESCRIPTION
**Pull request by ryota-ka**
[Snabbdom has reached v3 and its import paths have been changed](https://github.com/snabbdom/snabbdom/releases/tag/v3.0.0).

This pull request updates the dependency version and changes the codebase so that all the stuffs are imported from the single entrypoint.
(i.e., `import { foo } from 'snabbdom'`);

This will introduce a breaking change, so a major version bump is expected after this PR got merged.

### CODE REVIEW

**Comment by ryota-ka** [comment]
Hi @atomrc, pinging you for review. Sorry for interruption!

**Comment by atomrc** [comment]
Hi @ryota-ka , thanks for the PR. 
What do you think the Breaking Change would be? Just that the consumer needs to also use snabbdom 3 or is there something else that I am not seeing?

**Comment by atomrc** [comment]
@ryota-ka it's released with `v5.0.0`. Thanks again :)

**Comment by ryota-ka** [comment]
@atomrc Thank you!

---

> What do you think the Breaking Change would be?

I just meant that the v5.0.0 no longer supports Snabbdom v0.x.
(That is, "just that the consumer needs to also use snabbdom 3".)

**Pull request merged**
